apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-jop
spec:
  template:
    spec:
      containers:
      - name: mysql-init-container
        image: mysql:latest
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
               name: mysql-secrets
               key: root-password

        - name: MYSQL_AUTH_PASSWORD
          valueFrom:
             secretKeyRef:
               name: mysql-secrets
               key: user-password

        - name: MYSQL_HOST
          value: "mysql-headless-service"


        - name: MYSQL_PORT
          value: "3306"

        - name: MYSQL_USER
          value: "client"
        command: ["/bin/sh",-c]
        args:
         - | 
           mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -uroot -p${MYSQL_ROOT_PASSWORD} <<EOF
           CREATE DATABASE IF NOT EXISTS weatherapp;
           CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_AUTH_PASSWORD}';
           GRANT ALL PRIVILEGES ON weatherapp.* TO '${MYSQL_USER}'@'%';
           FLUSH PRIVILEGES;
           EOF

      restartPolicy: Never
